basis:
    epsilon:
        - 0.250
        - 0.200
        - 0.100
        - 0.050
        - 0.025
        - 0.020
        - 0.010
    L:
        - 1.0
    nstep:
        - 1
        - 2
        - 4
        - null
eigenvalues:
    solver:
        k: 200
    projector:
        type: a1g
        cutoff: 3.0E+02
physics:
    a_inv: 0.0
zeta:
    kind: spherical
    new: False
    N: 100
    improved: False
